# Generated by Django 4.1.2 on 2022-12-10 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("date_established", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("date_placed", models.DateTimeField()),
                ("item_count", models.BigIntegerField(default=0)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="points.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["customer_id", "-date_placed"],
            },
        ),
    ]
