# Generated by Django 4.1.2 on 2022-10-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BalanceSheet",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("person_id", models.UUIDField(unique_for_date="date_calculated")),
                ("date_calculated", models.DateTimeField()),
                ("assets", models.BigIntegerField(default=0)),
                ("liabilities", models.BigIntegerField(default=0)),
            ],
        ),
    ]
