version: '3.7'


volumes:
  postgres_data:


services:

  postgres:
    image: postgres:15

    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

    volumes:
      - postgres_data:/var/lib/postgresql/data/


  person-service-web:
    build: ./person-service
    env_file:
      - ./person-service/.env
    command:
      [
        "gunicorn",
        "--bind",
        "0.0.0.0:8001",
        "--reload",
        "service.wsgi"
      ]
    volumes:
     - ./person-service:/code
    depends_on:
      - postgres
    ports:
      - "8001:8001"
    environment:
      - DJANGO_READ_DOT_ENV_FILE=true
