# Generated by Django 4.1.2 on 2022-10-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("aggregatetype", models.CharField(max_length=255)),
                ("aggregateid", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField()),
                ("type", models.CharField(max_length=255)),
                ("payload", models.BinaryField()),
            ],
        ),
    ]
