# Generated by Django 4.1.2 on 2022-10-27 18:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_rename_type_event_event_type_event_content_type_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Event",
            new_name="OutboxItem",
        ),
    ]
