# Generated by Django 4.1.2 on 2022-10-27 18:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_rename_event_outboxitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="outboxitem",
            old_name="aggregateid",
            new_name="message_key",
        ),
        migrations.RenameField(
            model_name="outboxitem",
            old_name="aggregatetype",
            new_name="topic",
        ),
    ]
