# Generated by Django 4.1.2 on 2022-10-24 20:36

from django.db import migrations, models
import django_extensions.db.fields
import person.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(default="", max_length=50)),
                ("last_name", models.CharField(default="", max_length=50)),
                (
                    "date_of_birth",
                    models.DateTimeField(
                        blank=True, default=person.models.demo_date_of_birth, null=True
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
