# Generated by Django 4.1.2 on 2022-10-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50, null=True)),
                ("last_name", models.CharField(max_length=50, null=True)),
                ("date_of_birth", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
